# Generated by Django 2.2.1 on 2019-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madion',
            name='noe_madion',
            field=models.CharField(blank=True, choices=[('R', 'رهنی'), ('Z', 'لازم الاجرا')], default='m', help_text='Book availabi', max_length=1),
        ),
        migrations.AlterField(
            model_name='madion',
            name='kelase_asli',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='madion',
            name='kelase_niabati',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='madion',
            name='madion_zamen1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='madion',
            name='madion_zamen2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='madion',
            name='madion_zamen3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
